version: '3.9'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: &app
      context: ../..
      dockerfile: ./docker/local/app/Dockerfile
    restart: always
    command: /start-dev-server.sh
    depends_on:
      - db
    environment: &app-env
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - CLOUDFRONT_URL=${CLOUDFRONT_URL}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - FRONTEND_PASSWORD_RESET_URL=${FRONTEND_PASSWORD_RESET_URL}
      - FRONTEND_PROVIDERS_LOGIN_URL=${FRONTEND_PROVIDERS_LOGIN_URL}
    volumes: &code
      - ../..:/code
    ports:
      - 8000:8000

volumes:
  postgres_data:
